### ISSUE TITLE
ELF format selection

### ISSUE THREAD

**Issue by xatier** [HSAFoundation/HSAIL-Tools#35]
Hi,

The current `-elf64` flag will emit an ELF32 file.

Here's a simple patch for it, please take a look.

https://github.com/HSAFoundation/HSAIL-Tools/blob/master/libHSAIL%2FlibHSAIL%2FHSAILBrigObjectFile.cpp#L989

```C++
int BrigIO::save(BrigContainer &src,
                 int           fmt,
                 WriteAdapter& dst)
{
    if (fmt == FILE_FORMAT_BRIG) {
        return src.write(dst) ? 0 : 1;
    } 
+    if (fmt == FILE_FORMAT_ELF64) {
+    BrigIOImpl<Elf64Policy> impl(fmt);
-    BrigIOImpl<Elf32Policy> impl(fmt);
    return impl.writeContainer(&dst, src);
+ }
+   else  {
+    BrigIOImpl<Elf32Policy> impl(fmt);
+    return impl.writeContainer(&dst, src);
+ }

}
```

Also, the corresponding enumerators in `HSAILBrigObjectFile.h` should be fixed.

**Comment by vpykhtin** [comment]
Hi,

I committed the change that reflects your idea, should work now.

Thank you,
Valery

**Comment by xatier** [comment]
Hi @vpykhtin,

Thanks the following up.

But unfortunately this commit didn't fix the issue here, the expression of the switch `fmt & FILE_FORMAT_MASK` will never equal to `FILE_FORMAT_ELF64` (0x10), you need to change the corresponding values in the enumerator.

Thanks,

**Comment by vpykhtin** [comment]
Well there're actually two fields in fmt:

enum BinaryFileFormat {
    FILE_FORMAT_AUTO = 0,
    FILE_FORMAT_BRIG = 1,
    FILE_FORMAT_BIF  = 2,
    FILE_FORMAT_MASK = 0xf,
    FILE_FORMAT_ELF32 = 0,
    FILE_FORMAT_ELF64 = 0x10
};


fmt &  FILE_FORMAT_MASK tells which binary to choose - brig or bif

fmt & ~FILE_FORMAT_MASK tells the kind of elf

HSAILAsm selects formats as:

int format = (BifFileFormat ? FILE_FORMAT_BIF : FILE_FORMAT_BRIG)
                 | (Elf64FileFormat ? FILE_FORMAT_ELF64 : FILE_FORMAT_ELF32);

For the brig binary elf kind is just ignored.

Valery

**Comment by xatier** [comment]
in case if I use `./HSAILAsm -elf64`

`format` will be `FILE_FORMAT_BRIG | FILE_FORMAT_ELF64` which is 0x11 = 17

0x11 & FILE_FORMAT_BRIG = 1 = FILE_FORMAT_BRIG, that goes to emit Brig format.

Is that we need to use both `-bif` and `-elf64` flags together?

Thank you!

**Comment by vpykhtin** [comment]
You're right, but it seems a bit awkward now since brig isn't elf anymore. Should we select bif if -elf64 is  specified without the need to specify -bif?

**Comment by xatier** [comment]
I think so.

In my opinion, both `-elf64` and `-bif -elf64` will generate ELF64 files, `-bif` will generate ELF32.

That is more straightforward.

**Comment by vpykhtin** [comment]
Ok, I'll discuss this change with other people and commit this.

**Comment by xatier** [comment]
Thanks a lot!

**Comment by nhaustov** [comment]
-elf and -elf64 options look confusing to me, especially after 1.0f changes. ELF is also not very good name because it is generic format, not output format of hsailasm.

How about having the following:
-bif32 uses 32-bit BIF (ELF32 with BRIG in .brig section)
-bif64 uses 64-bit BIF (ELF64 with BRIG in .brig section)
-bif uses 32-bit/64-bit BIF depending on bitness of hsailasm
-brig uses BRIG (default)

Internally, BinaryFileFormat would be changed to:
enum BinaryFileFormat {
  FILE_FORMAT_AUTO = 0,
  FILE_FORMAT_BRIG = 1,
  FILE_FORMAT_BIF = 2,
  FILE_FORMAT_BIF32 = 3,
  FILE_FORMAT_BIF64 = 4,
};

**Comment by xatier** [comment]
Agree, that sounds more reasonable for me.

**Comment by vpykhtin** [comment]
I submitted the fix, but I decided not to introduce -bif flag that selects elf bitness depending on HSAILAsm bitness. I find it confusing. There're -bif32/-bif64 flags now. Also I changed the default extension for bif files from ".brig" to ".bif".
